version: '3.4'
services:
  api:
    container_name: doubtfire-api
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - web
    environment:
      DATABASE_URL: 'postgresql://itig:d872$$dh@db:5432/doubtfire_dev'
      RAILS_ENV: 'development'
      DF_DOCKER_MACHINE_IP: $DF_DOCKER_MACHINE_IP

  web:
    container_name: doubtfire-web
    build:
      context: ../doubtfire-web

  db:
    container_name: doubtfire-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: d872$$dh
      POSTGRES_USER: itig
